name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/jod"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Save build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          if-no-files-found: error
          path: dist
  lint:
    name: Format/Lint
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/jod"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Check Formatting
        run: pnpm format:check
      - name: Lint
        run: pnpm lint
  upload-deployment-artifact:
    name: Upload Deployment Artifact
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/jod"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist
      - name: Upload build files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: dist/
  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [upload-deployment-artifact]
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
